version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 2
  reviewers:
  - benjello
  ignore:
  - dependency-name: autopep8
    versions:
    - 1.5.5
    - 1.5.6
  - dependency-name: yamllint
    versions:
    - 1.25.0
  - dependency-name: flake8
    versions:
    - 3.8.0
